# Generated by Django 4.2.7 on 2023-12-05 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_rating'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='name',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to='products.product'),
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
